Repository xebia-functional/xef, pull requests merged in 2023-09, with the labels that each got.

#375 Refactor API service in its own function
  server/web/src/components/Pages/GenericQuestion/GenericQuestion.tsx
  server/web/src/utils/api/chatCompletions.ts
  server/web/src/utils/api/config.ts
  server/web/src/utils/api/index.ts
Labels: frontend

#387 Show Open AI library can talk to Xef server.
  server/src/main/kotlin/com/xebia/functional/xef/server/Server.kt
  server/web/package-lock.json
  server/web/package.json
  server/web/src/components/Pages/GenericQuestion/GenericQuestion.tsx
  server/web/src/utils/api/chatCompletions.ts
  server/web/src/utils/api/config.ts
Labels: openAI, frontend

#395 Web streaming example
  server/web/src/components/Pages/Chat/Chat.module.css
  server/web/src/components/Pages/Chat/Chat.tsx
  server/web/src/components/Pages/Chat/index.ts
  server/web/src/components/Pages/FeatureTwo/FeatureTwo.tsx
  server/web/src/components/Pages/FeatureTwo/index.ts
  server/web/src/components/Pages/GenericQuestion/GenericQuestion.tsx
  server/web/src/components/Sidebar/Sidebar.tsx
  server/web/src/main.tsx
  server/web/src/state/Settings/SettingsContext.tsx
  server/web/src/utils/api/chatCompletions.ts
  server/web/src/vite-env.d.ts
Labels: frontend, server
